---
title: "Homework 2"
author: "Weize Sun"
date: "10/6/2021"
output: github_document
---
```{r}
library(tidyverse)
```

## Problem 1

```{r}
trash_wheel_df = readxl::read_excel(
  "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N534") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round(sports_balls))
```


```{r}
pre_19 = readxl::read_excel(
  "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "2019 Precipitation",
  range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2019) %>% 
  relocate(year)

pre_18 = readxl::read_excel(
  "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "2018 Precipitation",
  range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

pre_1819 = full_join(pre_18, pre_19) %>% 
  mutate(month = month.name[month])

pre_1819
```

```{r}
sum(pull(pre_18, total))
ball_19 = filter(trash_wheel_df, year == 2019)
median(pull(ball_19, sports_balls))
```

** The observation of trash_wheel_df is 345 with 14 variables, and we are specifically paying attention to variable *sports_balls*. The observation of pre_1819 is 24, and we are specifically looking at variable *total*. For available data, the total precipitation in 2018 is 70.33, and the median number of sports balls in a dumpster in 2019 is 9. **







